### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by schmidtw** [mborges-pivotal/artifactory-resource#1]

**Comment by mborges-pivotal** [comment]
I created as an open source project for anyone to use. It was taken over by pivotal service a while back and should also be freely available. See the link in the readme.

**Comment by schmidtw** [comment]
Thanks for creating this.  It is widely used.  I would like to work on some enhancements but with no license (MIT, BSD, GPL) it means that I can't safely do that or really use the code.

The pivotal link in the readme does not work.  Is there an updated one?
